# Generated by Django 3.2.7 on 2021-09-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='', max_length=502),
        ),
    ]
